images:
  image:
    repository: plexinc/pms-docker
    tag: 1.41.3.9292-bc7397402
  plex_pass_image:
    repository: plexinc/pms-docker
    tag: plexpass

consts:
  plex_container_name: plex
  perms_container_name: permissions
  internal_web_port: 32400
